// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EamaShop.Client.Identity.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// 图片信息
    /// </summary>
    public partial class ImageInfoDTO
    {
        /// <summary>
        /// Initializes a new instance of the ImageInfoDTO class.
        /// </summary>
        public ImageInfoDTO() { }

        /// <summary>
        /// Initializes a new instance of the ImageInfoDTO class.
        /// </summary>
        public ImageInfoDTO(string uri = default(string))
        {
            Uri = uri;
        }

        /// <summary>
        /// 图片的路径
        /// </summary>
        [JsonProperty(PropertyName = "Uri")]
        public string Uri { get; private set; }

    }
}
