// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EamaShop.Client.Identity.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultDTO
    {
        /// <summary>
        /// Initializes a new instance of the ResultDTO class.
        /// </summary>
        public ResultDTO() { }

        /// <summary>
        /// Initializes a new instance of the ResultDTO class.
        /// </summary>
        public ResultDTO(string message = default(string))
        {
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; private set; }

    }
}
