// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EamaShop.Client.Identity.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// 接口返回对象的基础结构
    /// </summary>
    public partial class ResultDTOWrapper
    {
        /// <summary>
        /// Initializes a new instance of the ResultDTOWrapper class.
        /// </summary>
        public ResultDTOWrapper() { }

        /// <summary>
        /// Initializes a new instance of the ResultDTOWrapper class.
        /// </summary>
        public ResultDTOWrapper(string message = default(string))
        {
            Message = message;
        }

        /// <summary>
        /// 返回的结果描述信息，如果状态码为错误，则为错误信息
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; private set; }

    }
}
