// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EamaShop.Client.Identity
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for IdentityClient.
    /// </summary>
    public static partial class IdentityClientExtensions
    {
            /// <summary>
            /// 使用jwtBearer授权
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// 账号： 手机号/邮箱/用户名
            /// </param>
            /// <param name='password'>
            /// 用户密码
            /// </param>
            public static object ApiAuthorizeJwtbearerPost(this IIdentityClient operations, string name, string password)
            {
                return Task.Factory.StartNew(s => ((IIdentityClient)s).ApiAuthorizeJwtbearerPostAsync(name, password), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 使用jwtBearer授权
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// 账号： 手机号/邮箱/用户名
            /// </param>
            /// <param name='password'>
            /// 用户密码
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiAuthorizeJwtbearerPostAsync(this IIdentityClient operations, string name, string password, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiAuthorizeJwtbearerPostWithHttpMessagesAsync(name, password, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// 获取当前的用户信息
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            public static object ApiUserGet(this IIdentityClient operations, string authorization)
            {
                return Task.Factory.StartNew(s => ((IIdentityClient)s).ApiUserGetAsync(authorization), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 获取当前的用户信息
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiUserGetAsync(this IIdentityClient operations, string authorization, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiUserGetWithHttpMessagesAsync(authorization, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// 修改用户基础信息
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='nickName'>
            /// 修改后的昵称
            /// </param>
            /// <param name='headImageUri'>
            /// 修改后的用户头像Uri地址
            /// </param>
            /// <param name='sexy'>
            /// 修改后的性别
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            /// <param name='country'>
            /// 修改后的用户所在国家
            /// </param>
            /// <param name='city'>
            /// 修改后的用户所在城市
            /// </param>
            /// <param name='province'>
            /// 修改后的用户所在省份
            /// </param>
            public static void ApiUserPut(this IIdentityClient operations, string nickName, string headImageUri, int sexy, string authorization, string country = default(string), string city = default(string), string province = default(string))
            {
                Task.Factory.StartNew(s => ((IIdentityClient)s).ApiUserPutAsync(nickName, headImageUri, sexy, authorization, country, city, province), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 修改用户基础信息
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='nickName'>
            /// 修改后的昵称
            /// </param>
            /// <param name='headImageUri'>
            /// 修改后的用户头像Uri地址
            /// </param>
            /// <param name='sexy'>
            /// 修改后的性别
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            /// <param name='country'>
            /// 修改后的用户所在国家
            /// </param>
            /// <param name='city'>
            /// 修改后的用户所在城市
            /// </param>
            /// <param name='province'>
            /// 修改后的用户所在省份
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiUserPutAsync(this IIdentityClient operations, string nickName, string headImageUri, int sexy, string authorization, string country = default(string), string city = default(string), string province = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApiUserPutWithHttpMessagesAsync(nickName, headImageUri, sexy, authorization, country, city, province, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// 注册
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='accountName'>
            /// 用于注册的用户名 8~18个字符之间
            /// </param>
            /// <param name='password'>
            /// 用于注册的密码 6~18个字符之间
            /// </param>
            /// <param name='headImageUri'>
            /// 头像地址的绝对路径
            /// </param>
            /// <param name='nickName'>
            /// 用户的昵称
            /// </param>
            public static IDictionary<string, string> ApiUserPost(this IIdentityClient operations, string accountName, string password, string headImageUri, string nickName)
            {
                return Task.Factory.StartNew(s => ((IIdentityClient)s).ApiUserPostAsync(accountName, password, headImageUri, nickName), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 注册
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='accountName'>
            /// 用于注册的用户名 8~18个字符之间
            /// </param>
            /// <param name='password'>
            /// 用于注册的密码 6~18个字符之间
            /// </param>
            /// <param name='headImageUri'>
            /// 头像地址的绝对路径
            /// </param>
            /// <param name='nickName'>
            /// 用户的昵称
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IDictionary<string, string>> ApiUserPostAsync(this IIdentityClient operations, string accountName, string password, string headImageUri, string nickName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiUserPostWithHttpMessagesAsync(accountName, password, headImageUri, nickName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// 修改密码接口
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='newPassword'>
            /// 设置的新密码
            /// </param>
            /// <param name='token'>
            /// 用户修改密码的凭证 短信为验证码，邮箱也为验证码
            /// </param>
            public static void ApiUserPasswordPut(this IIdentityClient operations, string newPassword, string token)
            {
                Task.Factory.StartNew(s => ((IIdentityClient)s).ApiUserPasswordPutAsync(newPassword, token), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 修改密码接口
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='newPassword'>
            /// 设置的新密码
            /// </param>
            /// <param name='token'>
            /// 用户修改密码的凭证 短信为验证码，邮箱也为验证码
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiUserPasswordPutAsync(this IIdentityClient operations, string newPassword, string token, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApiUserPasswordPutWithHttpMessagesAsync(newPassword, token, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// 绑定手机号码
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='phone'>
            /// 手机号码
            /// </param>
            /// <param name='verifyCode'>
            /// 验证码
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            public static void ApiUserPhonePut(this IIdentityClient operations, string phone, string verifyCode, string authorization)
            {
                Task.Factory.StartNew(s => ((IIdentityClient)s).ApiUserPhonePutAsync(phone, verifyCode, authorization), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 绑定手机号码
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='phone'>
            /// 手机号码
            /// </param>
            /// <param name='verifyCode'>
            /// 验证码
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiUserPhonePutAsync(this IIdentityClient operations, string phone, string verifyCode, string authorization, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApiUserPhonePutWithHttpMessagesAsync(phone, verifyCode, authorization, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// 修改用户角色为商户 该接口不会对外提供，只能在当前测试页面进行查看
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            public static void ApiUserRoleByIdPut(this IIdentityClient operations, long id, string authorization)
            {
                Task.Factory.StartNew(s => ((IIdentityClient)s).ApiUserRoleByIdPutAsync(id, authorization), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 修改用户角色为商户 该接口不会对外提供，只能在当前测试页面进行查看
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='authorization'>
            /// 身份认证的授权token eg. Bearer ej
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiUserRoleByIdPutAsync(this IIdentityClient operations, long id, string authorization, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApiUserRoleByIdPutWithHttpMessagesAsync(id, authorization, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// 发送验证码给指定的手机号
            /// 接口未实现，默认使用验证码123456
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='phone'>
            /// 用户的手机号码
            /// </param>
            public static void ApiVerifycodePhonePost(this IIdentityClient operations, string phone = default(string))
            {
                Task.Factory.StartNew(s => ((IIdentityClient)s).ApiVerifycodePhonePostAsync(phone), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 发送验证码给指定的手机号
            /// 接口未实现，默认使用验证码123456
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='phone'>
            /// 用户的手机号码
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiVerifycodePhonePostAsync(this IIdentityClient operations, string phone = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApiVerifycodePhonePostWithHttpMessagesAsync(phone, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// 发送邮箱验证码到指定邮箱
            /// 接口未实现，默认使用验证码123456
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='email'>
            /// </param>
            public static void ApiVerifycodeEmailPost(this IIdentityClient operations, string email = default(string))
            {
                Task.Factory.StartNew(s => ((IIdentityClient)s).ApiVerifycodeEmailPostAsync(email), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// 发送邮箱验证码到指定邮箱
            /// 接口未实现，默认使用验证码123456
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='email'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiVerifycodeEmailPostAsync(this IIdentityClient operations, string email = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApiVerifycodeEmailPostWithHttpMessagesAsync(email, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
